### ISSUE TITLE
Race condition when updating a function

### ISSUE THREAD

**Issue by scothis** [projectriff-archive/function-controller#5] opened 2018-01-24 21:47 UTC
When using `riff update` to update a deployed function, sometimes (~50%) the creation of the new function is rejected because the previous function is still being deleted `Error object is being deleted: deployments.extensions "square" already exists`. When this error occurs, calls to `riff publish` hang.

After deleting the function-controller pod, a new controller starts and correctly recognizes the updated function.

```
2018/01/24 21:27:57 Scaling square to 0
2018/01/24 21:27:57 Deployment added/updated: square
2018/01/24 21:27:57 Deployment added/updated: square
2018/01/24 21:27:57 Deployment added/updated: square
2018/01/24 21:27:58 Topic deleted: square
2018/01/24 21:27:58 Function deleted: square
2018/01/24 21:27:58 Deployment added/updated: square
2018/01/24 21:27:58 Deployment added/updated: square
2018/01/24 21:27:58 Function added: square
2018/01/24 21:27:58 Error object is being deleted: deployments.extensions "square" already exists
2018/01/24 21:27:58 Topic added: square
```

**Comment by glyn** [comment] 2018-02-08 16:14
Reproduced this. Note to self: `Error object is being deleted: deployments.extensions "square" already exists` appears in the function-controller logs.

We are [not alone](https://github.com/openfaas/faas-cli/issues/217) in tripping over this behaviour.

**Comment by glyn** [comment] 2018-02-08 16:19
Relevant portion of function-controller logs:
```
16:17:53 Function deleted: square
16:17:53 Deployment added/updated: square
16:17:53 Deployment added/updated: square
16:17:53 Topic deleted: numbers
16:17:54 Function added: square
16:17:54 Error object is being deleted: deployments.extensions "square" already exists
16:17:54 Topic added: numbers
```

**Comment by glyn** [comment] 2018-02-08 16:54
With some debugger breakpoints in the function-controller, it works correctly:
```
16:45:24 Function deleted: square
16:46:27 Deployment added/updated: square
16:46:27 Topic added: numbers
16:46:27 Topic deleted: numbers
16:47:42 Deployment deleted: square
16:47:42 Function added: square
16:47:50 Deployment added/updated: square
16:47:51 Deployment added/updated: square
16:47:53 Deployment added/updated: square
16:47:54 Deployment added/updated: square
```
Interestingly, we don't see `Deployment deleted: square` in the logs of the failing case.

**Comment by glyn** [comment] 2018-02-09 13:56
Adding `--force=true` to the `kubectl apply` in `riff` appears to solve this issue. The `kubectl` documentation says
>  --force=false: Delete and re-create the specified resource, when PATCH encounters conflict and
> has retried for 5 times.

## Alternatives

- When I attempted to work around the problem in function-sidecar, the deleted deployment hung around for 70 seconds or so (!), so that approach is far less attractive than the `--force=true` fix.

- A better solution in the longer term is for the `riff` CLI to issue an update and function-controller to implement issue https://github.com/projectriff/function-controller/issues/9. There could still be an issue if users explicitly deleted and re-created a function in quick succession, but hopefully they would learn not to do it. PR https://github.com/projectriff/function-controller/pull/15 might help there.

**Comment by glyn** [comment] 2018-02-16 08:56
`riff update` using the Go CLI now updates the function resource and PR https://github.com/projectriff/function-controller/pull/16 acts accordingly. With those changes, it will be more difficult to reproduce this bug. We should probably defer PR https://github.com/projectriff/function-controller/pull/15 unless this becomes an issue for users because the cure may be as bad as the disease.

**Comment by jldec** [comment] 2018-02-21 19:18
Closing this for now while we reprioritize work on function controller.

**Closed as completed by jldec** 2018-02-21 19:18 UTC
Labels: bug
